### ISSUE TITLE
Ethernet Not Workign

### ISSUE THREAD

**Issue by sherifabdlnaby** [sjoerdvz/Opencore-Aorus-Elite-AC#1]
Hello, I just bought Z490 Arous Elite AC And tried using your bootloader.

Everything is perfect, thank you! Except for Ethernet. It shows Cable Disconnected, and I tried to set configuration Manually as I read in forums but it doesn't work either.

Have you met this with your setup?
I am using Motherboard BIOS version F6 tho...

**Comment by sjoerdvz** [comment]
yes you need to set it Manuel to 100 T-base full duplex  in network settings like so 
dont forget to save your settings  now all will working 

https://www.google.com/search?q=realtek+full+duplex+lan+not+working+catalina&tbm=isch&ved=2ahUKEwjFmpfB9cXuAhXVOuwKHbFRBM8Q2-cCegQIABAA&oq=realtek+full+duplex+lan+not+working+catalina&gs_lcp=CgNpbWcQA1Dp_QFYtZQCYKSVAmgAcAB4AIABLogBgASSAQIxMpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=XIAWYMX8J9X1sAexo5H4DA&bih=969&biw=1920#imgrc=vjkO2Wo4zUgWkM


________________________________
Van: Sherif Abdel-Naby <notifications@github.com>
Verzonden: zondag 31 januari 2021 01:34
Aan: sjoerdvz/Opencore-Aorus-Elite-AC <Opencore-Aorus-Elite-AC@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjoerdvz/Opencore-Aorus-Elite-AC] Ethernet Not Workign (#1)


Hello, I just bought Z490 Arous Elite AC And tried using your bootloader.

Everything is perfect, thank you! Except for Ethernet. It shows Cable Disconnected, and I tried to set configuration Manually as I read in forums but it doesn't work either.

Have you met this with your setup?
I am using Motherboard BIOS version F6 tho...

**Comment by sherifabdlnaby** [comment]
Thank you, although I tried what you did right here, it didn't work. Turns out, I forgot vt-d option in BIOS enabled. When I disabled it Ethernet worked. 👍🏻
