### ISSUE TITLE
Bluetooth Issues

### ISSUE THREAD

**Issue by sherifabdlnaby** [sjoerdvz/Opencore-Aorus-Elite-AC#2]
Hello,

Everything is working fine now except Bluetooth Mic Input. Have you had that?

I don't have a PCI-E Fenvi card, I am using the onboard WIFI+BT. Bluetooth is unstable and can't use devices mics.

**Comment by sjoerdvz** [comment]
i use the the stock onboard to. i use a mic wireless  game controllers and magic keybord on it 
for mic you need to set audio input in audio pannel 
try the new bootloader this one have new drivers for wifi and bluetooth that working better
